[workspace]
resolver = "2"

members = [
    "mutiny-core",
    "mutiny-wasm",
]


# Tell `rustc` to optimize for small code size.
[profile.release.package.mutiny-core]
opt-level = "z"

[profile.release.package.mutiny-wasm]
opt-level = "z"

[patch.crates-io]
lightning = { git = 'https://github.com/MutinyWallet/rust-lightning.git', rev = "0e2c116d1fa9d8db25e0364466dcacf4c7366c33" }
lightning-invoice = { git = 'https://github.com/MutinyWallet/rust-lightning.git', rev = "0e2c116d1fa9d8db25e0364466dcacf4c7366c33" }
lightning-rapid-gossip-sync = { git = 'https://github.com/MutinyWallet/rust-lightning.git', rev = "0e2c116d1fa9d8db25e0364466dcacf4c7366c33" }
lightning-background-processor = { git = 'https://github.com/MutinyWallet/rust-lightning.git', rev = "0e2c116d1fa9d8db25e0364466dcacf4c7366c33" }
lightning-transaction-sync = { git = 'https://github.com/MutinyWallet/rust-lightning.git', rev = "0e2c116d1fa9d8db25e0364466dcacf4c7366c33" }
lightning-net-tokio = { git = 'https://github.com/MutinyWallet/rust-lightning.git', rev = "0e2c116d1fa9d8db25e0364466dcacf4c7366c33" }
